############################
### fuzzel configuration ###
############################

include=~/.config/fuzzel/themes/catppuccin-macchiato/mauve.ini

prompt=">> "
icons-enabled=yes
fields=filename,name,generic
#fields=name,generic,filename,categories,keywords,comment
delayed-filter-ms=400
delayed-filter-limit=20000
show-actions=yes
terminal=kitty -e
anchor=center
lines=10
horizontal-pad=20
image-size-ratio=0.5
match-mode=fzf

# font=monospace
# dpi-aware=auto
# use-bold=no
# placeholder=
# icon-theme=default
# hide-before-typing=no
# password-character=*
# filter-desktop=no
# sort-result=yes
# match-counter=no
# launch-prefix=<not set>
# list-executables-in-path=no

# x-margin=0
# y-margin=0
# minimal-lines=no
# width=30
# tabs=8
# vertical-pad=8
# inner-pad=0

# scaling-filter=box
# image-size-ratio=0.5

# gamma-correct-blending=no
# line-height=<use font metrics>
# letter-spacing=0

# cache=<not set>

[border]
width=2
radius=17
selection-radius=25

[dmenu]
mode=text  # text|index
exit-immediately-if-empty=yes
