# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0A0A1B)
$foreground = rgb(DDF8FA)
$color0 = rgb(424744)
$color1 = rgb(77B0B6)
$color2 = rgb(AE9BBC)
$color3 = rgb(7992B6)
$color4 = rgb(759274)
$color5 = rgb(937476)
$color6 = rgb(7C6799)
$color7 = rgb(C7ECF0)
$color8 = rgb(8BA5A8)
$color9 = rgb(9FEAF2)
$color10 = rgb(E8CEFB)
$color11 = rgb(A2C2F3)
$color12 = rgb(9CC29A)
$color13 = rgb(C49A9D)
$color14 = rgb(A589CC)
$color15 = rgb(C7ECF0)
