###############################
### HyprPaper Configuration ###
###############################

preload = $HOME/Pics/Wallpapers/emba.jpg
wallpaper = eDP-1, $HOME/Pics/Wallpapers/emba.jpg

splash = true #enable splash text rendering over wallpaper

ipc = off #disable ipc (for performance)
