#################
### Autostart ###
#################

# startup
exec-once = systemctl --user import-environment WAYLAND XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start hyprpolkitagent # start hyprland implementation of polkit_agent
exec-once = swaync-client -t -sw # notification daemon
exec-once = hyprsunset # bluelight filtering protocal
exec-once = hypride # idling protocal

# startup apps
exec-once = hyprpaper --config ~/.config/hypr/scripts/Wallpaper.sh & waybar #when it actually looks nice
exec-once = network-manager-applet --indicator
exec-once = $terminal & swaync
