###################
### Input rules ###
###################

input {
	kb_layout = us
	kb_variant =
	kb_model =
	kb_options =
	kb_rules =

	follow_mouse = 1

	sensitivity = 0 # [-1.0, 1.0] where 0 means no modification

	touchpad {
		natural_scroll = false # inverts scrolling
		disable_while_typing = true
		scroll_factor = 1.1 # 1.0 is default value
		tap-to-click = true

		# 1 + click = left mouse button
		# 2 + click = right mouse button
		# 3 + click = middle mouse button
	}

	gestures {
	}
}

#device {
#	name = funnyNameHere
#}
