###############
### Monitor ###
###############

# monitor = eDP-1, 2560x1600@60, 0x0, 1 # Mac default 16:10 aspect ratio (very small)
 monitor = eDP-1, 1728x1080@60, 0x0, 1 # custom 16:10 aspect ratio (normal)
# monitor = ,preferred,auto,auto # external monitor default config
