###############
### Monitor ###
###############

# monitor = ,preferred,auto,auto # external monitor default config
monitor = DP-1, 1920x1080@164.997, 0x0, 1
monitor = HDMI-A-1, 1920x1080@74.973, 1920x0, 1
