#################
### Variables ###
#################

env = EDITOR, nvim
$edit=${EDITOR: -nano} # if neovim shits the bed then nano takes the spot

# Set programs that you use

$terminal = kitty
$fileManager = thunar
$menu = rofi
$browser = librewolf
$DocViewer = okular
$textEditor = subl # sublime text
