##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#
windowrule = tag +browser, class:^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$ # browser tag
windowrule = tag +notif, class:^(swaync-control-center|swaync-notifications-window|swaync-client|class)$ # notif tag
windowrule = tag +terminal, class:^(kitty|kitty-dropterm)$ # terminal tag
windowrule = tag +im, class:^([Dd]iscord|[Dd]iscordo)$ # insant messaging tag
windowrule = tag +file-manager, class:^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$ # file manager tag

# settings tags
windowrule = tag +settings, class:^(gnome-disks|wihotspot(-gui)?)$
windowrule = tag +settings, class:^(nm-applet|nm-connection-editor)$
windowrule = tag +settings, class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$
windowrule = tag +settings, class:^(qt5ct|qt6ct|[Yy]ad)$
windowrule = tag +settings, class:(xdg-desktop-portal-gtk)
windowrule = tag +settings, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = tag +settings, class:^([Rr]ofi)$

# positon
windowrule = center, class:([Tt]hunar), title:negative(.*[Tt]hunar.*) 
windowrule = center, class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$

# float
windowrule = float, tag:settings*
windowrule = float, tag:viewer*

# float popups and dialogue
windowrule = float, title:^(Authentication Required)$
windowrule = center, title:^(Authentication Required)$
windowrule = float, class:^([Tt]hunar), title:negative:(.*[Tt]hunar.*)

windowrule = float, title:^(Add Folder to Workspace)$
windowrule = size 70% 60%, title:^(Add Folder to Workspace)$
windowrule = center, title:^(Add Folder to Workspace)$

windowrule = float, title:^(Save As)$
windowrule = size 70% 60%, title:^(Save As)$
windowrule = center, title:^(Save As)$

windowrule = float, initialTitle:(Open Files)
windowrule = size 70% 60%, initialTitle:(Open Files)

# opacity
windowrule = opacity 0.9 0.7, tag:browser*
windowrule = opacity 0.95 0.86, tag:im*
    windowrule = opacity 0.95 0.85, tag:file-manager*
windowrule = opacity 0.95 0.85, tag:terminal*
windowrule = opacity 0.8 0.7, tag:settings*

# layer rules
layerrule = blur, rofi
layerrule = ignorezero, rofi
layerrule = blur, notifications
layerrule = ignorezero, notifications
